version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - derKrischan
  ignore:
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "< 3.9"
  - dependency-name: org.assertj:assertj-core
    versions:
    - "< 3.0.0"
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - 3.12.0
