# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: maven:3.6-jdk-7-slim

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run build and unit tests
      - run: mvn package

  analyze:
    docker:
      - image: circleci/openjdk:11.0.5-jdk-stretch
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:  
      - checkout

      - run: mvn package
      
      # static code analysis
      - run: mvn sonar:sonar -Dsonar.projectKey=derKrischan_jpdftest -Dsonar.organization=derkrischan-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
  
  finish-feature:
    docker:
      # specify the version you desire here
      - image: maven:3.6-jdk-7-slim

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: 
          command: |
            git branch -r | grep -v '\->' | grep -v 'master' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
            git pull --all

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run build and unit tests
      - run: 
          command: |
            export FEATURE_BRANCH_NAME=`git log --first-parent --merges -1 --oneline develop | sed 's/[0-9a-f]* Merge pull request #[0-9]* from \(.*\)/\1/'`
            echo "Finishing feature in branch ${FEATURE_BRANCH_NAME}"
            if [[ ! "${FEATURE_BRANCH_NAME}" =~ ^feature/[a-zA-Z0-9_#\-]*$ || -z "${FEATURE_BRANCH_NAME}" ]]; then
              echo "No merge after feature branch pull request. Stopping build.";
              exit 1;
            fi
            export FEATURE_NAME=`echo ${FEATURE_BRANCH_NAME} | sed 's/^feature\///'`
            echo "Merging feature ${FEATURE_NAME}"
            mvn -U -B gitflow:feature-finish -DversionProcessAllModules=true -DinstallProject=false -DskipTestProject=true -DskipFeatureVersion=false -DallowSnapshots=true -DpushRemote=true -DfeatureName="${FEATURE_NAME}"
  
workflows:
  version: 2
  build_and_analyze_feature:
    jobs:
      - finish-feature:
          filters:
            branches:
              only: develop
      - build
      - analyze:
          requires:
            - build

